name: SentinelOne CNS Scan

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master, main]

jobs:
  s1-shift-left-cli:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1-shift-left-cli:0.5.2
      options: --entrypoint ""

    env:
      # Required secret
      S1_SERVICE_USER_API_TOKEN: ${{ secrets.S1_SERVICE_USER_API_TOKEN }}
      # Your fixed values
      S1_MANAGEMENT_CONSOLE_URL: https://usea1-purple.sentinelone.net
      S1_SCOPE_TYPE: ACCOUNT
      S1_SCOPE_ID: "1881212418608401729"
      S1_POLICY_TAG: prod-scan-policy

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure SentinelOne CNS CLI
        run: |
          s1-cns-cli config \
            --service-user-api-token "${S1_SERVICE_USER_API_TOKEN}" \
            --management-console-url "${S1_MANAGEMENT_CONSOLE_URL}" \
            --scope-type "${S1_SCOPE_TYPE}" \
            --scope-id "${S1_SCOPE_ID}" \
            --tag "${S1_POLICY_TAG}"

      - name: Mark repo as safe
        run: git config --global --add safe.directory "$PWD"

      - name: Secret Scan (PR commits)
        id: secret
        continue-on-error: true
        env:
          DEST: ${{ github.event.pull_request.base.sha }}
          SRC: ${{ github.event.pull_request.head.ref }}
          REPO_FULL_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}
        run: |
          s1-cns-cli scan secret -d "$PWD" \
            --pull-request origin/$SRC $DEST \
            --publish-result \
            --repo-full-name "$REPO_FULL_NAME" \
            --repo-url "$REPO_URL/$REPO_FULL_NAME" \
            --provider GITHUB

      - name: IaC Scan (working tree)
        id: iac
        continue-on-error: true
        env:
          REPO_FULL_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          s1-cns-cli scan iac -d "$PWD" \
            --publish-result \
            --repo-full-name "$REPO_FULL_NAME" \
            --repo-url "$REPO_URL/$REPO_FULL_NAME" \
            --branch "$BRANCH" \
            --provider GITHUB

      - name: Vulnerability Scan (filesystem)
        id: vuln
        continue-on-error: true
        run: |
          s1-cns-cli scan vuln -d "$PWD"

      - name: Fail if any scan failed (policy-driven)
        if: steps.secret.outcome == 'failure' || steps.iac.outcome == 'failure' || steps.vuln.outcome == 'failure'
        run: exit 1
