name: SentinelOne CNS Scan

on:
  pull_request:
    branches: [main]

jobs:
  cns-scan:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1-shift-left-cli:0.5.1
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v4

      - name: Configure SentinelOne CNS CLI
        run: >
          s1-cns-cli config
          --service-user-api-token ${{ S1_SERVICE_USER_API_TOKEN }}
          --management-console-url https://usea1-purple.sentinelone.net
          --scope-type SITE
          --scope-id 2271127775668844387
          --tag ${{ secrets.tag }}

      - name: Run Secret Detector
        run: >
          s1-cns-cli scan secret -d $PWD --publish-result
